###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"Bharath",
    "username":"bharath4578",
    "password": "Bharath@456",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"bharath4578",
    "password": "Bharath@456"
}